### ISSUE TITLE
Disconnect causing EOF errors

### ISSUE THREAD

**Issue by 5tanly** [ammaraskar/pyCraft#113]
This is the code I am using to reconnect/connect to the server

> async def reco(self):
>     try:
>         self.connection.disconnect()
>         await asyncio.sleep(60)
>     except:
>         pass
>     self.connection.connect()
>     await asyncio.sleep(3)
>     packet = serverbound.play.ChatPacket()
>     packet.message = '/server witch'
>     self.connection.write_packet(packet)
>     print('Logged In')

This is the error I get when I execute that code (only happens at the `self.connection.disconnect()` line from what I can see i.e. when reconnecting)

> Exception in thread Networking Thread:
> Traceback (most recent call last):
>   File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/minecraft/networking/connection.py", line 462, in run
>     self._run()
>   File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/minecraft/networking/connection.py", line 496, in _run
>     self.connection.file_object, timeout=read_timeout)
>   File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/minecraft/networking/connection.py", line 535, in read_packet
>     length = VarInt.read(stream)
>   File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/minecraft/networking/types/basic.py", line 113, in read
>     raise EOFError("Unexpected end of message.")
> EOFError: Unexpected end of message.
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last):
>   File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/threading.py", line 917, in _bootstrap_inner
>     self.run()
>   File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/minecraft/networking/connection.py", line 466, in run
>     self.connection._handle_exception(e, sys.exc_info())
>   File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/minecraft/networking/connection.py", line 412, in _handle_exception
>     raise_(*exc_info)
>   File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/future/utils/__init__.py", line 415, in raise_
>     raise exc.with_traceback(tb)
>   File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/minecraft/networking/connection.py", line 462, in run
>     self._run()
>   File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/minecraft/networking/connection.py", line 496, in _run
>     self.connection.file_object, timeout=read_timeout)
>   File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/minecraft/networking/connection.py", line 535, in read_packet
>     length = VarInt.read(stream)
>   File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/minecraft/networking/types/basic.py", line 113, in read
>     raise EOFError("Unexpected end of message.")
> EOFError: Unexpected end of message.

Sorry for the garbage formatting I don't know how GitHub works with codeblocks, tilda doesnt seem to respect my tabs/enters

**Comment by 5tanly** [comment]
No matter how or where I use `self.connection.disconnect(immediate=True)` i always get EOF errors
