### ISSUE TITLE
Error whilst connecting to server

### ISSUE THREAD

**Issue by Zyrexus** [ammaraskar/pyCraft#114]
I'm getting this error while connecting, I'm not sure why but here it is:

`Exception in thread Networking Thread:
Traceback (most recent call last):
  File "C:\Python27\lib\threading.py", line 801, in __bootstrap_inner
    self.run()
  File "C:\Users\jake4\Desktop\Testing\pyCraft-master\minecraft\networking\connection.py", line 466, in run
    self.connection._handle_exception(e, sys.exc_info())
  File "C:\Users\jake4\Desktop\Testing\pyCraft-master\minecraft\networking\connection.py", line 412, in _handle_exception
    raise_(*exc_info)
  File "C:\Users\jake4\Desktop\Testing\pyCraft-master\minecraft\networking\connection.py", line 462, in run
    self._run()
  File "C:\Users\jake4\Desktop\Testing\pyCraft-master\minecraft\networking\connection.py", line 477, in _run
    while not self.interrupt and self.connection._pop_packet():
  File "C:\Users\jake4\Desktop\Testing\pyCraft-master\minecraft\networking\connection.py", line 234, in _pop_packet
    self._write_packet(self._outgoing_packet_queue.popleft())
  File "C:\Users\jake4\Desktop\Testing\pyCraft-master\minecraft\networking\connection.py", line 247, in _write_packet
    packet.write(self.socket)
  File "C:\Users\jake4\Desktop\Testing\pyCraft-master\minecraft\networking\packets\packet.py", line 98, in write
    self.write_fields(packet_buffer)
  File "C:\Users\jake4\Desktop\Testing\pyCraft-master\minecraft\networking\packets\packet.py", line 107, in write_fields
    data_type.send(data, packet_buffer)
  File "C:\Users\jake4\Desktop\Testing\pyCraft-master\minecraft\networking\types\basic.py", line 79, in send
    socket.send(struct.pack('>H', value))
error: cannot convert argument to integer`

The code I'm using here is just a stripped down version of the start.py (removed the enter server details and username & password - I just hardcoded it in to save time whilst making it.)

**Comment by BluCobalt** [comment]
What was the problem, if you don't mind me asking? I have the same thing.
