### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'context'

### ISSUE THREAD

**Issue by FoxNerdSaysMoo** [ammaraskar/pyCraft#200]
I ran `start.py` with -d enabled, and I logged on successfully, but a few seconds after logging on there was a error message (below). I ran it in a bash repl on repl.it, on a 1.16.3 vanilla server. It ran perfectly when -d was not enabled, and it worked when I switched `print('--> [unknown packet] %s' % packet, file=sys.stderr)` to `print(type(packet))`. 
Error message:

> Exception in thread Networking Thread:
Traceback (most recent call last):
  File "/usr/lib/python3.8/threading.py", line 932, in _bootstrap_inner
    self.run()
  File "/opt/virtualenvs/python3/lib/python3.8/site-packages/minecraft/networking/connection.py", line 552, in run
    self.connection._handle_exception(e, sys.exc_info())
  File "/opt/virtualenvs/python3/lib/python3.8/site-packages/minecraft/networking/connection.py", line 495, in _handle_exception
    raise exc_value.with_traceback(exc_tb)
  File "/opt/virtualenvs/python3/lib/python3.8/site-packages/minecraft/networking/connection.py", line 548, in run
    self._run()
  File "/opt/virtualenvs/python3/lib/python3.8/site-packages/minecraft/networking/connection.py", line 586, in _run
    self.connection._react(packet)
  File "/opt/virtualenvs/python3/lib/python3.8/site-packages/minecraft/networking/connection.py", line 522, in _react
    listener.call_packet(packet)
  File "/opt/virtualenvs/python3/lib/python3.8/site-packages/minecraft/networking/packets/packet_listener.py", line 15, in call_packet
    self.callback(packet)
  File "main.py", line 92, in print_incoming
    print('--> [unknown packet] %s' % packet, file=sys.stderr)
  File "/opt/virtualenvs/python3/lib/python3.8/site-packages/minecraft/networking/packets/packet.py", line 118, in __repr__
    fields = self.fields
  File "/opt/virtualenvs/python3/lib/python3.8/site-packages/minecraft/networking/packets/packet.py", line 128, in fields
    if self.definition is None:
  File "/opt/virtualenvs/python3/lib/python3.8/site-packages/minecraft/networking/types/utility.py", line 185, in __get__
    return self._fget(instance)
  File "/opt/virtualenvs/python3/lib/python3.8/site-packages/minecraft/networking/packets/packet.py", line 43, in definition
    self.get_definition(self.context)
  File "/opt/virtualenvs/python3/lib/python3.8/site-packages/minecraft/networking/packets/packet.py", line 38, in get_definition
    return getattr(cls, 'definition')
  File "/opt/virtualenvs/python3/lib/python3.8/site-packages/minecraft/networking/types/utility.py", line 185, in __get__
    return self._fget(instance)
  File "/opt/virtualenvs/python3/lib/python3.8/site-packages/minecraft/networking/packets/packet.py", line 42, in definition
    return None if self.context is None else \
AttributeError: 'NoneType' object has no attribute 'context'

There were also 2 packets before it, and one really long one (here are the small ones)

> --> 0x17 PluginMessagePacket(channel='minecraft:brand', data=b'\x07vanilla')
--> 0x0D ServerDifficultyPacket(difficulty=EASY, is_locked=False)

**Comment by FoxNerdSaysMoo** [comment]
I am using a new program now that no longer has this problem, and can close this unless anyone wants to solve it
