### ISSUE TITLE
Error on disconnect()

### ISSUE THREAD

**Issue by datatags** [ammaraskar/pyCraft#214]
I'm using this tool to simply connect to a server, send a chat packet or two, and disconnect every once in a while.  This is my code:
```python
        conn.connect()
        sleep(3)
        conn.write_packet(message_packet)
        sleep(2)
        for name in needs_money:
            money_packet.message = "/pay " + name + " 1000"
            conn.write_packet(money_packet)
            sleep(2)
        conn.disconnect()
```
I've set up the authentication, server connection, and message/money packets earlier, that all works.  The error pops up when conn.disconnect() is called, although the connection does seem to close normally, based on the message in the server console.  Here's the error:
```
Exception in thread Networking Thread:
Traceback (most recent call last):
  File "/usr/lib/python3.7/threading.py", line 917, in _bootstrap_inner
    self.run()
  File "/usr/local/lib/python3.7/dist-packages/pyCraft-0.7.0-py3.7.egg/minecraft/networking/connection.py", line 589, in run
    self.connection._handle_exception(e, sys.exc_info())
  File "/usr/local/lib/python3.7/dist-packages/pyCraft-0.7.0-py3.7.egg/minecraft/networking/connection.py", line 532, in _handle_exception
    raise exc_value.with_traceback(exc_tb)
  File "/usr/local/lib/python3.7/dist-packages/pyCraft-0.7.0-py3.7.egg/minecraft/networking/connection.py", line 585, in run
    self._run()
  File "/usr/local/lib/python3.7/dist-packages/pyCraft-0.7.0-py3.7.egg/minecraft/networking/connection.py", line 619, in _run
    self.connection.file_object, timeout=read_timeout)
  File "/usr/local/lib/python3.7/dist-packages/pyCraft-0.7.0-py3.7.egg/minecraft/networking/connection.py", line 659, in read_packet
    length = VarInt.read(stream)
  File "/usr/local/lib/python3.7/dist-packages/pyCraft-0.7.0-py3.7.egg/minecraft/networking/types/basic.py", line 154, in read
    byte = file_object.read(1)
  File "/usr/local/lib/python3.7/dist-packages/pyCraft-0.7.0-py3.7.egg/minecraft/networking/encryption.py", line 71, in read
    return self.decryptor.update(self.actual_file_object.read(length))
  File "/usr/lib/python3.7/socket.py", line 583, in readinto
    self._checkClosed()
ValueError: I/O operation on closed file.
```
I'm not super familiar with python, so I'm not sure if there are some troubleshooting steps I could take to figure this out, or if I'm simply doing something wrong.

Thanks!

Also I should mention, the script continues running after it prints the error, and using a try-except block doesn't prevent it from displaying.

**Comment by datatags** [comment]
Project is abandoned
