### ISSUE TITLE
ImportError: DLL load failed while importing _openssl: %1 is not a valid Win32 application.

### ISSUE THREAD

**Issue by svfeplvce** [ammaraskar/pyCraft#216]
This is an error I keep getting when trying to use PyCraft. I have no idea what could possibly be wrong. I have installed and reinstalled cryptography and followed the instructions of other fellow devs to no avail. If anyone could help me figure this out, it'd be very much appreciated. Here's the full error:
```Exception in thread Networking Thread:
Traceback (most recent call last):
  File "C:\Python39\lib\threading.py", line 954, in _bootstrap_inner
    self.run()
  File "C:\Python39\lib\site-packages\minecraft\networking\connection.py", line 589, in run
    self.connection._handle_exception(e, sys.exc_info())
  File "C:\Python39\lib\site-packages\minecraft\networking\connection.py", line 532, in _handle_exception
    raise exc_value.with_traceback(exc_tb)
  File "C:\Python39\lib\site-packages\minecraft\networking\connection.py", line 585, in run
    self._run()
  File "C:\Python39\lib\site-packages\minecraft\networking\connection.py", line 623, in _run
    self.connection._react(packet)
  File "C:\Python39\lib\site-packages\minecraft\networking\connection.py", line 560, in _react
    self.reactor.react(packet)
  File "C:\Python39\lib\site-packages\minecraft\networking\connection.py", line 721, in react
    token, encrypted_secret = encryption.encrypt_token_and_secret(
  File "C:\Python39\lib\site-packages\minecraft\networking\encryption.py", line 28, in encrypt_token_and_secret
    pubkey = load_der_public_key(pubkey, default_backend())
  File "C:\Python39\lib\site-packages\cryptography\hazmat\backends\__init__.py", line 15, in default_backend
    from cryptography.hazmat.backends.openssl.backend import backend
  File "C:\Python39\lib\site-packages\cryptography\hazmat\backends\openssl\__init__.py", line 7, in <module>
    from cryptography.hazmat.backends.openssl.backend import backend
  File "C:\Python39\lib\site-packages\cryptography\hazmat\backends\openssl\backend.py", line 117, in <module>
    from cryptography.hazmat.bindings.openssl import binding
  File "C:\Python39\lib\site-packages\cryptography\hazmat\bindings\openssl\binding.py", line 14, in <module>
    from cryptography.hazmat.bindings._openssl import ffi, lib
ImportError: DLL load failed while importing _openssl: %1 is not a valid Win32 application.```

**Comment by ammaraskar** [comment]
How'd you install cryptography? A wide variety of reasons can cause this error, including installing the wrong version (32-bit vs 64-bit) of the library compared to your Python version. We can try to help you out a little bit but this might be better handled by the cryptography folks.

**Comment by svfeplvce** [comment]
> How'd you install cryptography? A wide variety of reasons can cause this error, including installing the wrong version (32-bit vs 64-bit) of the library compared to your Python version. We can try to help you out a little bit but this might be better handled by the cryptography folks.

It was automatically installed originally as part of the installation of PyCraft but when I reinstalled it, I used both `pip install cryptography` and `pip install --force-reinstall cryptography`.

**Comment by svfeplvce** [comment]
Update: I found out that the wrong version was automatically installed and managed to fix it by installing it via the wheel provided on PyPi
