### ISSUE TITLE
Error when connecting to a server

### ISSUE THREAD

**Issue by bettercalldelta** [ammaraskar/pyCraft#225]
So I tried to write my first pycraft code, which was basically the rewrite of start.py with some unimportant things removed.

But it keeps displaying me this error when I start the file:
```Traceback (most recent call last):
  File "no i will not give the path/connect.py", line 15, in <module>
    connection.connect()
  File "no i will not give the path/minecraft/networking/connection.py", line 245, in connect
    self._connect()
  File "no i will not give the path/minecraft/networking/connection.py", line 275, in _connect
    self.socket.connect((self.options.address, self.options.port))
socket.gaierror: [Errno -2] Name or service not known```

I thought "socket" module doesn't recognize the ip, so I triple checked the hostname and port. It is right. But the error is still there.

**Comment by mindforger** [comment]
could you provide a bare minimum of details what options you used (with fake data if you are concerned)? you just told basically
>i changed something and it does not work

which is similar to say i worked on the motor of my car and now it does not run ...

**Comment by Cassy-Lee** [comment]
it look like something wrong with your DNS
