### ISSUE TITLE
Updating to 1.17 Issues

### ISSUE THREAD

**Issue by MisterSoandSo** [ammaraskar/pyCraft#228]
I ran into the following issue after updating to 755 protocol standard and ran into the following in my [current fork of the repository:](https://github.com/MisterSoandSo/pyCraft/commit/6400602625b4d897655edddda7492b5a8d60b125) . However, I ran into network threading error after updating the player_list_item_packet.py's  packet id to 1.17 standard. Unless there is something different done in network side for 1.17. I'm currently a bit clueless. I've tested this on a local host of 1.17 vanilla.

 ![connect locally](https://i.imgur.com/w6pnnEd.png)

```
Exception in thread Networking Thread:
Traceback (most recent call last):
  File "C:\Users\acs21\AppData\Local\Programs\Python\Python38\lib\threading.py", line 932, in _bootstrap_inner     
    self.run()
  File "c:\Users\acs21\Documents\GitHub\pyCraft\minecraft\networking\connection.py", line 589, in run
    self.connection._handle_exception(e, sys.exc_info())
  File "c:\Users\acs21\Documents\GitHub\pyCraft\minecraft\networking\connection.py", line 532, in _handle_exception
    raise exc_value.with_traceback(exc_tb)
  File "c:\Users\acs21\Documents\GitHub\pyCraft\minecraft\networking\connection.py", line 585, in run
    self._run()
  File "c:\Users\acs21\Documents\GitHub\pyCraft\minecraft\networking\connection.py", line 618, in _run
    packet = self.connection.reactor.read_packet(
  File "c:\Users\acs21\Documents\GitHub\pyCraft\minecraft\networking\connection.py", line 689, in read_packet
    packet.read(packet_data)
  File "c:\Users\acs21\Documents\GitHub\pyCraft\minecraft\networking\packets\packet.py", line 69, in read
    value = data_type.read_with_context(file_object, self.context)
  File "c:\Users\acs21\Documents\GitHub\pyCraft\minecraft\networking\types\basic.py", line 29, in read_with_context
    return cls_or_self.read(file_object)
  File "c:\Users\acs21\Documents\GitHub\pyCraft\minecraft\networking\types\basic.py", line 231, in read
    return struct.unpack('>f', file_object.read(4))[0]
struct.error: unpack requires a buffer of 4 bytes
```

**Comment by MisterSoandSo** [comment]
Okay I had a derp moment and didn't realize I didn't update all protocols besides the one's listed in init.py However, I ran into another issue I tried to [resolve.](https://github.com/MisterSoandSo/pyCraft/commit/0169e0aa75fd39ad3de3a03599ec7528ea70abce) 
Apparently in Player Position And Look (clientbound),  they added a new field 'Dismount Vehicle' after a bit of backtracking in the 754 protocol for 1.16.5 in debug mode.
```
--> 0x18 PluginMessagePacket(channel='minecraft:brand', data=b'\x07vanilla')
--> 0x0E ServerDifficultyPacket(difficulty=PEACEFUL, is_locked=False)
Exception in thread Networking Thread:
Traceback (most recent call last):
  File "C:\Users\acs21\AppData\Local\Programs\Python\Python38\lib\threading.py", line 932, in _bootstrap_inner
    self.run()
  File "c:\Users\acs21\Documents\GitHub\pyCraft\minecraft\networking\connection.py", line 589, in run
    self.connection._handle_exception(e, sys.exc_info())
  File "c:\Users\acs21\Documents\GitHub\pyCraft\minecraft\networking\connection.py", line 532, in _handle_exception
    raise exc_value.with_traceback(exc_tb)
  File "c:\Users\acs21\Documents\GitHub\pyCraft\minecraft\networking\connection.py", line 585, in run
    self._run()
  File "c:\Users\acs21\Documents\GitHub\pyCraft\minecraft\networking\connection.py", line 618, in _run
    packet = self.connection.reactor.read_packet(
  File "c:\Users\acs21\Documents\GitHub\pyCraft\minecraft\networking\connection.py", line 689, in read_packet
    packet.read(packet_data)
  File "c:\Users\acs21\Documents\GitHub\pyCraft\minecraft\networking\packets\packet.py", line 69, in read
    value = data_type.read_with_context(file_object, self.context)
  File "c:\Users\acs21\Documents\GitHub\pyCraft\minecraft\networking\types\basic.py", line 29, in read_with_context
    return cls_or_self.read(file_object)
  File "c:\Users\acs21\Documents\GitHub\pyCraft\minecraft\networking\types\basic.py", line 348, in read
    return pynbt.NBTFile(io=file_object)
  File "C:\Users\acs21\AppData\Local\Programs\Python\Python38\lib\site-packages\pynbt.py", line 368, in __init__
    raise IOError('NBTFile does not begin with 0x0A.')
OSError: NBTFile does not begin with 0x0A.
```
Anyone familiar with this error?

**Comment by MisterSoandSo** [comment]
More debugging I found that it reading a dimension packet when it suppose to read an x coordinate packet
1.16.5 version output
```
dict_items([('difficulty', <class 'minecraft.networking.types.basic.UnsignedByte'>)])
dict_items([('is_locked', <class 'minecraft.networking.types.basic.Boolean'>)])
--> 0x0D ServerDifficultyPacket(difficulty=HARD, is_locked=False)
dict_items([('x', <class 'minecraft.networking.types.basic.Double'>)])
dict_items([('y', <class 'minecraft.networking.types.basic.Double'>)])
dict_items([('z', <class 'minecraft.networking.types.basic.Double'>)])
dict_items([('yaw', <class 'minecraft.networking.types.basic.Float'>)])
dict_items([('pitch', <class 'minecraft.networking.types.basic.Float'>)])
dict_items([('flags', <class 'minecraft.networking.types.basic.Byte'>)])
dict_items([('teleport_id', <class 'minecraft.networking.types.basic.VarInt'>)])
--> 0x34 PlayerPositionAndLookPacket(x=278.46797047141115, y=44.0, z=-309.70161643627773, yaw=-275.048583984375, pitch=37.20003890991211, flags=0, teleport_id=1)
--> 0x32 PlayerListItemPacket(action_type=AddPlayerAction, actions=[AddPlayerAction(
```

vs 1.17 output
```
dict_items([('channel', <class 'minecraft.networking.types.basic.String'>)])
dict_items([('data', <class 'minecraft.networking.types.basic.TrailingByteArray'>)])
--> 0x18 PluginMessagePacket(channel='minecraft:brand', data=b'\x07vanilla')
dict_items([('difficulty', <class 'minecraft.networking.types.basic.UnsignedByte'>)])
dict_items([('is_locked', <class 'minecraft.networking.types.basic.Boolean'>)])
--> 0x0E ServerDifficultyPacket(difficulty=PEACEFUL, is_locked=False)
dict_items([('dimension', <class 'minecraft.networking.types.basic.NBT'>)])
Exception in thread Networking Thread:
```
I'm just confused why it decided to read join_game_and_respawn packet when it should be player position packet.

**Comment by MisterSoandSo** [comment]
Fixed the issue myself after tinker around in debug for a few hours.
