### ISSUE TITLE
Avoiding 1.17

### ISSUE THREAD

**Issue by isaackogan** [ammaraskar/pyCraft#229]
Currently, 1.17 is not supported.

Traceback (most recent call last):
  File "/usr/local/lib/python3.8/threading.py", line 932, in _bootstrap_inner
    self.run()
  File "/home/container/.local/lib/python3.8/site-packages/minecraft/networking/connection.py", line 589, in run
    self.connection._handle_exception(e, sys.exc_info())
  File "/home/container/.local/lib/python3.8/site-packages/minecraft/networking/connection.py", line 532, in _handle_exception
    raise exc_value.with_traceback(exc_tb)
  File "/home/container/.local/lib/python3.8/site-packages/minecraft/networking/connection.py", line 585, in run
    self._run()
  File "/home/container/.local/lib/python3.8/site-packages/minecraft/networking/connection.py", line 623, in _run
    self.connection._react(packet)
  File "/home/container/.local/lib/python3.8/site-packages/minecraft/networking/connection.py", line 560, in _react
    self.reactor.react(packet)
  File "/home/container/.local/lib/python3.8/site-packages/minecraft/networking/connection.py", line 828, in react
    self.handle_status(status_dict)
  File "/home/container/.local/lib/python3.8/site-packages/minecraft/networking/connection.py", line 858, in handle_status
    self.connection._version_mismatch(
  File "/home/container/.local/lib/python3.8/site-packages/minecraft/networking/connection.py", line 550, in _version_mismatch
    raise err
minecraft.exceptions.VersionMismatch: Server's protocol version of 755 (BungeeCord 1.8.x-1.17.x) is not supported.

I was wondering if anyone knew how I might go about specifying a specific version, not only for 1.17 but just the future in general.

 I have zero issue connecting via an older Minecraft version as the server I run my bot on will be supporting as far back as 1.8.9 forever, I just don't know how to specify that I want 1.16 instead of 1.17 when connecting. 

Any assistance appreciated!

**Comment by MisterSoandSo** [comment]
Well considering the library written to handle up to protocol 755 (1.17), the library needs to updated to handle it. I'm currently working on the  issue privately on different fork #228

**Comment by Hiiva** [comment]
connection = Connection(
            options.address, options.port, auth_token=auth_token, allowed_versions=[340])

this is for 1.12.2

**Comment by isaackogan** [comment]
Thank you, this is exactly what I was looking for.
