### ISSUE TITLE
EOFError: Unexpected end of message (on connect())

### ISSUE THREAD

**Issue by DAMcraft** [ammaraskar/pyCraft#237]
my client connects to the server but then i get the following error:

`  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.9_3.9.2288.0_x64__qbz5n2kfra8p0\lib\threading.py", line 973, in _bootstrap_inner
    self.run()
  File "c:\users\damia\appdata\local\packages\pythonsoftwarefoundation.python.3.9_qbz5n2kfra8p0\localcache\local-packages\python39\site-packages\pyCraft\minecraft\networking\connection.py", line 589, in run
    self.connection._handle_exception(e, sys.exc_info())
  File "c:\users\damia\appdata\local\packages\pythonsoftwarefoundation.python.3.9_qbz5n2kfra8p0\localcache\local-packages\python39\site-packages\pyCraft\minecraft\networking\connection.py", line 532, in _handle_exception      
    raise exc_value.with_traceback(exc_tb)
  File "c:\users\damia\appdata\local\packages\pythonsoftwarefoundation.python.3.9_qbz5n2kfra8p0\localcache\local-packages\python39\site-packages\pyCraft\minecraft\networking\connection.py", line 585, in run
    self._run()
  File "c:\users\damia\appdata\local\packages\pythonsoftwarefoundation.python.3.9_qbz5n2kfra8p0\localcache\local-packages\python39\site-packages\pyCraft\minecraft\networking\connection.py", line 618, in _run
    packet = self.connection.reactor.read_packet(
  File "c:\users\damia\appdata\local\packages\pythonsoftwarefoundation.python.3.9_qbz5n2kfra8p0\localcache\local-packages\python39\site-packages\pyCraft\minecraft\networking\connection.py", line 659, in read_packet
    length = VarInt.read(stream)
  File "c:\users\damia\appdata\local\packages\pythonsoftwarefoundation.python.3.9_qbz5n2kfra8p0\localcache\local-packages\python39\site-packages\pyCraft\minecraft\networking\types\basic.py", line 157, in read
    raise EOFError("Unexpected end of message.")
EOFError: Unexpected end of message.`

I have no idea how to fix it, but this part raises the error:
![image](https://user-images.githubusercontent.com/43420467/141654409-d9a20221-97a3-438b-ae19-32e3cd764646.png)
printing byte gives me an empty BYTE-type

**Comment by joodicator** [comment]
@DAMcraft Is the server you're trying to connect to a public one? Is it a vanilla server, or is it running any mods? Do you know at what point in the connection process this error occurs? (The `--dump-packets` flag to `start.py` might be useful.) It's hard to diagnose the problem from the above, but it sounds like the server may be terminating the connection early due to some kind of protocol error or authentication failure.

**Comment by 0xseck** [comment]
I have the same problem. It's a public server with some plugins. Here is the output with --dump-packets flag:

```
Connecting in offline mode...
<-- 0x00 HandShakePacket(protocol_version=9999, server_address='mc.gamerway.online', server_port=25565, next_state=1)
<-- 0x00 RequestPacket()
--> 0x00 ResponsePacket(json_response='{"version":{"protocol":758,"name":"Velocity 1.7.2-1.18.2"},"players":{"online":14,"max":500,"sample":[{"name":"§7Gamerway\\u0027e hoşgeldin §eUykucuSirin","id":"00000000-0000-0000-0000-000000000000"},{"name":"","id":"00000000-0000-0000-0000-000000000000"},{"name":"  - §aHub: §e0 kişi aktif","id":"00000000-0000-0000-0000-000000000000"},{"name":"  - §aTowny: §e14/100 kişi aktif","id":"00000000-0000-0000-0000-000000000000"},{"name":"  - §aPvP: §e0/100 kişi aktif","id":"00000000-0000-0000-0000-000000000000"},{"name":"","id":"00000000-0000-0000-0000-000000000000"},{"name":"  ","id":"00000000-0000-0000-0000-000000000000"}]},"description":{"extra":[{"text":"           "},{"color":"red","text":"✰ "},{"color":"dark_red","text":"✯ "},{"color":"red","text":"✰ "},{"bold":true,"color":"dark_red","text":"GAMERWAY "},{"color":"red","text":"✰ "},{"color":"dark_red","text":"✯ "},{"color":"red","text":"✰\\n                      "},{"color":"white","text":"Pvp - "},{"color":"white","text":"Towny"}],"text":""},"favicon":"data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAEAAAABACAYAAACqaXHeAAANq0lEQVR4Xu1aCVQUVxb9rE0jgiACQoPNDgIqiCyCrKIEIwg0KmuMIEZRFPd9HQWNqFEQsSGCGFeI0bggouCCCu7CqLiiRk9ycuJgnGhGjW/eK2mmLWJi5oyAc/qe805VV/3/679bb/u/mjEFFFBAAQUUUEABBRRQ4H8NNTU17hgVFaW7du3ajwsLC+dIJBLxuHHj0vbv359fWloqJdm1a9eXQ4cOjZ45c6ZjUVHRohUrVgSHhIRoHzt2jDfiB4Tp06eziIgI7fXr1ycfOXLkdG1t7dOrV69CXl7exh49ehw5ePAg3LlzBxoaGugamJmZFezbt29nfX09XLp06SkSU5GZmTnUw8NDc/jw4fzh2y+MjIwYALA5c+b0RIW+qaure06KyuT8+fNPXVxcGiMjI+HGjRtw6tQpcHJyAnzjD65du/ZM1u727dtw8eLFpzt37iwaO3as1d27d5lAIOA/rn0B3ywdlNCEQ0+cOHH91q1bzcrIBBWBDRs2gKGhIaxatQqSkpKga9eugG7AWYN8W+pLJB06dOjs3LlzPYlYPT09/mPbB6ytrbkjKjW0urr6e3lFZMqQ8nQ8efIkeHp6gq6eHgg1NYGsAS3jjTbyfYnIo0ePXp0/f74n9m2OLe0GKioqrLy8nOEEA3CCD2QK0Bu9d+8ep8Dp06e5Nx8XHw/WdrbQSVMLLDT0wFBDGzpoaYG9owNnDQUFBXD27NkWZNAY+IzqlJQUMT6HP4W2RUJCAgsNDe1y4MCBYzKlb968CcePH4esrCzALABisRg6dERFDU0h2dAVCmwjnx/qmVi/1fmTa/PtBv0r2MgRjDR0QCgUgrWtDcQnxINUKuWIIwJkY2JM+AIfqdKvXz/+NNoGysrKDKM2y83NHYFB62VlZSVg9AYkBEQiEaiqqnI+PmzYMNiQnwe1Bd/Cba/p93Z1j41bIg4SfW71sclul1FhpR7js7e5j65d7BT57GMTZxBpontoaIDY0gKGRw+H7HXZXMCsqan5IT09vTcSy59K24DMn4ITpqrc4OBgMDAwAPRRMDY2BktLS+6crIAs4+79e/DdyUtwI3je1Wm67kZpIm9ujD4dzZgWU1VeYhNmsMt9XEhpv6mrdnhPPL/UJfaX8G4eYNahCwgFGmDazQxCw0IhbMiQ1AkTJ/Jm0kbQ1NTkREtLawbmci6grV69GjALcPldR0cHtmzZwpnw7TsYF+quwb3YFT9JjT9y3mgTyR+OWQj16aC0wC5Cv7jvpP4H/Odm7PSbUZPZZ9yTRPMI6Klt89xYaDBcR0WLiTQN+d1bD7GxsSw8PFyI5j6opKTki7KysisU3SlYkbIUwKqqqsDBwQF27NjB/eaywc1b8CBN+mK3eVT4mV5j+MO+AZGAS3lKM+3DdXd4Zfge9v9ycanfhsMHfHPL9vnkrChwXzpwhPkQ4XibWH7X9w8sbVlGRoYn+uQjCk4Urfl5/Pr161wALC4ubibgdsMdeLi8GCrtR0yDQIpn7wYNFXXuGC8e3GF9n/nOX3t/kVYRUFBd6LE0YJf3Gl7rVgAWLhT4wq5cufKCn7dlQoQsX74c9u7d+x8C7jbAw83lcKZ3Sh6No6/WgT/0OwEuAENrWPO195r4i8Ff82+/f5w7d47h4iYRy9cWisuEiKE0JityZBbw3aEaqPOfWeHGjDQHdrbjD/1OgFFP2H7f9Qu+9cme+Diymn/7/YMi//bt22dSqUqKke+TycvqAFkRI5NmYvD83rk6uCHJuDFX399khvkA/tDNKHBfwpx0rFUXOKZ02dL3cxf0/dhy//wFmz2XhcDInxgqPwFJWASfveR3ff8gAtANVsn8H2sAGDlyJCQnJ3M1/u7duylnA63u3iAFzxvqb0DDmJxGqVlEn0LHBG68QQa9mKWmgcpcm3C9r1zGOu3znBtR7i+df8g/r2RXvzW1G/osfDSre/Jvy3pOAvT9ItiIz/deE3fQb8NauA282b1naGho0EEJ1/Sb6c3LLCA6OppmAlgcgba2NlhZWUH//v1hzJgxzaScOXMGbmH7+wu3viyxSRh61HUCkxi7C3a5TRp10HPmthK3tAs5PRN/nGMb9SJBPBi8u7iAqWZXEKoIuLHTbBOgzC9v8oOwSrbda2XIIb+8TXhdRU9d5405vldYWFjQQR1XaQdkpk1vd926dVzhg/daiIwUOzs72FFSDN/nHYTyXmPmNAauZJtdUjy/ch33yEffHkyFnVFZ9Rb9SbTVtGCTR/pPRR7LXDEFsk0eGX3RJUoGdvUWuuo5vp5ca8DX15d5eXlpY9lbI/NvMnOqA5CcFhPny8hRSfBgz0k45T2liFypvO+sBUndAlq044tbZydAl6iQmA7Umu84lm3os8DhSMCXeyfbjdCNMhvIWg0xMTG0AOqKCtfLBzhyA7zeYuJ8sUUruLC7HC6HLq6K1nM12+cx7aSDtqhFO3lRUVKGafaJRMAcmAoMlWYrek01OxKw8cDyXpNFk2w/Ya2G0aNHMwx2Flju3pcvfoiM6upqSE1N5TY82O8oQqKmrg7SlWvhVlLWrfzunyat7THiZ4Gyaot2JEpMCey0zeFvPSb8hsqfWNt7tn2R5zKW57aI4Xn3Y4GbTqx0nm6NmaJpdq0ANH+mq6urMW3atI20QuOTQEcqfiQSCeAaoYVSJMMkUXBjSn7jvt5px2NEXi3uk3QVdoFUmzjY57v+dpmfdDqavRGlPDR7Ut4S/b8cidjqb+iuGSceLJte6wAJoJWg9ZAhQy7Tur+50pMLilQX0AYHZoJfBAJBHXa7g/IMBczE3aBm8rpXVV5zX4o1u8iUfo7yUEtV826EKOjl9r6ZP1YEbFyT1XsOVUtK3bUt2bmBOxn+tkLlK6fYfVpvIjTo7tTJRm5mrYimdBgVGBj4+NixYy3WAjIirl69+gJTYA2mySRs74+Spaym8ltOzFTIc00GZSXlF3htPUpYsmXUtG/6ra056CctwELI3VnXXnWoWTAT4Frg7yF7MPAt7I7KHx9pEfGLQFk9zlbbXH5KrYtRo0ax+Ph4N7FYfNbT0/NVRUVFC0uQdwtMk4ewG23tWqE0DHDwgOBuvenN16OYogh3eK0s+9Zn3UTrjt3U8A1zz9HFHN8YeZqUd8AV4clhZh+BvbbFtUTLSJfPrIY1z6fVUVpaynDNH4sl8WNzc/MXbm5ucPjw4beSsHDhwgbsJkZRQikUqKmDQJXL+blqyqo0pAUGtHq0gP57fdZxzyDl/yk5S2WxMwbBMxLTAdCjky3GhZwnJd6rg7A8bppNG4AWRPn5+aPJ15EE+rgBzs7OIPvowXeFKVOmPMVuAU3do9hrn/8VJYwYQQQtchr/D1R+wAFf8gjGzqLPS/ss7IUl7/lQE39w6mQN2/quuIsV4JltfTMHoTs0DdcGuH//PlnAJKr3ScGioiIu/WFMIL9/gwS6TyUxdktt6m6Mcg2FgqNsaydtun3iy1Lf3FBMb9wFKpQw6md9ah4OFloiKPRIv49uMmh3v6yMnV6rok72/6qpaxugsbGRCJhBBJCStDAKCgr61cfH5zF/mUwBEmMGESC/m0nn8rsi2VjQAK7zQ48HFnEXYBlWiv75n+Pb/xcGQ8DCZxnkA64E1y3hCAjaIte9lYGKs5ycnAmkLL3turo6coGXWCk+5scAOQKkckN4oLjTSZMLSPkE/CypYZgRUjDqPw009KCFUBZZBfp+VrH36jhykTZDZmYmmzFjhiPWAddIQdr8MDU1hZSUlBaB8C0EkN6c7m8j4HTQVlI2coZ90steunYU/Epy+ywYVBlQUJnVe7YjuoRsrNaHSCTifHT16tURFy9efIRZAbBAgiVLlrzeBf5zAprxNgIw4NG63wvr/icWWqaAvn8X3eAUBkAJpAITdzCRG6UN4O3N7e0rb926dTa6wwsqfWk7/PcIoE9f7C8SsKznZFbosdQm323xQ5GmIWCGeIFuMBtvKQ82oZqqHQCLIYY5viOWvBvRAl7RxsfvucB/Q8AoyyiW3jOtCwa8OnEHY8BskC91W6RFq8H2CH17e/sCLItf8cti+p2YmPiXCQgx9mEJ5mEd0ferfLq4bsZL3JeTdokJEyawuLg40/Ly8tPyyssIoD1D9m4EhFN+t+poxmjtj28/ujKgsGKe4xgxrv3f7NieQIujqqoqlp6e7ldTU/NQvhCic3SVtxLQBOk46xhMddKYyx99Q9Gf5bjOcz4aWHiiyHNZ8LOoC0xHrSO/T/tC079EmFQqTamtreX+8iIjAOuDPyVgjNUwjgBygVndkw0w4u/ByJ+G95TQBfjt2yckEgmzs7MTFhcX59I6gUdANr+9HLJfE5AXg+fKaAGrsAjKDTUJEKZYR/Pbtm/MmjWLYdQXlZWVHZf9V6iJgJX8tnJYSQTs910fjfV+Au33LXZKFa1xmcVv1/6hqqrK9uzZQ+nR69SpU/coCDZ9N/hDAnB9D1j4ZKPyh/PcFnlSJaispMxv92HAysqKqxSzs7OTLl++/PRdLGC8TSxcGFjyA1aA8bAZmIMO7Z18wAgJCWH6+vqCbdu2rYmIiPhTAsgCMABmCFUEajHdBvHvf5gYP348S01NNbK2tqZFPpWxb8NsZ137vBXOUzvPc/jjP098qKD9wD/6iEf32vnfQRVQQAEFFFBAgf8X/BvYi0jHWdAQwQAAAABJRU5ErkJggg\\u003d\\u003d"}')
<-- 0x00 HandShakePacket(protocol_version=758, server_address='mc.gamerway.online', server_port=25565, next_state=2)
<-- 0x00 LoginStartPacket(name='UykucuSirin')
--> 0x03 SetCompressionPacket(threshold=256)
--> 0x02 LoginSuccessPacket(UUID='4a377999-7c4b-3f19-8331-6e2fb1efb682', Username='UykucuSirin')
Exception in thread Networking Thread:
Traceback (most recent call last):
  File "/usr/lib/python3.9/threading.py", line 973, in _bootstrap_inner
    self.run()
  File "/home/seck/pyCraft/minecraft/networking/connection.py", line 596, in run
    self.connection._handle_exception(e, sys.exc_info())
  File "/home/seck/pyCraft/minecraft/networking/connection.py", line 539, in _handle_exception
    raise exc_value.with_traceback(exc_tb)
  File "/home/seck/pyCraft/minecraft/networking/connection.py", line 592, in run
    self._run()
  File "/home/seck/pyCraft/minecraft/networking/connection.py", line 625, in _run
    packet = self.connection.reactor.read_packet(
  File "/home/seck/pyCraft/minecraft/networking/connection.py", line 666, in read_packet
    length = VarInt.read(stream)
  File "/home/seck/pyCraft/minecraft/networking/types/basic.py", line 156, in read
    raise EOFError("Unexpected end of message.")
EOFError: Unexpected end of message.
```
