### ISSUE TITLE
"ModuleNotFoundError: No module named 'mutf8'"

### ISSUE THREAD

**Issue by d3ttl4ff** [ammaraskar/pyCraft#273]
Traceback (most recent call last):
  File "/home/kali/Desktop/crafty/pyCraft/start.py", line 10, in <module>
    from minecraft.networking.connection import Connection
  File "/home/kali/Desktop/crafty/pyCraft/minecraft/networking/connection.py", line 12, in <module>
    from .types import VarInt
  File "/home/kali/Desktop/crafty/pyCraft/minecraft/networking/types/__init__.py", line 1, in <module>
    from .basic import *    # noqa: F401, F403
    ^^^^^^^^^^^^^^^^^^^^
  File "/home/kali/Desktop/crafty/pyCraft/minecraft/networking/types/basic.py", line 9, in <module>
    import pynbt
  File "/usr/local/lib/python3.11/dist-packages/PyNBT-3.1.0-py3.11.egg/pynbt.py", line 23, in <module>
ModuleNotFoundError: No module named 'mutf8'

It says its not found even though I have installed the pyNBT library multiple times

**Comment by aipul96** [comment]
Same problem?

**Comment by aipul96** [comment]
Have any one got solution for this ?

**Comment by d3ttl4ff** [comment]
> Have any one got solution for this ?

I think there was workaround. But I don't remember what I did now. Been a long time 🥲

**Comment by RapidEdwin08** [comment]
I know this is late, but I'm using **_python3-venv_** as a solution for the same issue with another utility and wanted to share.

## Python 3.1x+ mutf8/pynbt Errors
Traceback (most recent call last):
  File "/home/pi/.mcpiedit/./main.py", line 8, in <module>
    from pynbt import NBTFile, TAG_String, TAG_Long, TAG_Int, TAG_Short, TAG_List, TAG_Compound, TAG_Byte
  File "/usr/local/lib/python3.11/dist-packages/PyNBT-3.1.0-py3.11.egg/pynbt.py", line 23, in <module>
ModuleNotFoundError: No module named 'mutf8'

Traceback (most recent call last):
  File "/home/pi/.mcpiedit/./main.py", line 8, in <module>
    from pynbt import NBTFile, TAG_String, TAG_Long, TAG_Int, TAG_Short, TAG_List, TAG_Compound, TAG_Byte
ModuleNotFoundError: No module named 'pynbt'

```sh
sudo apt-get install python3-mutf8 # Unable to locate package python3-mutf8
sudo dpkg -i ~/python3-mutf8_1.0.6-2+b2_arm64.deb # Error: Dependency is not satisfiable: python3 (>=3.13~)
```
## How To Run in isolated virtual environment
```sh
# Install mcpiedit prerequisites
sudo apt-get install python3-venv # Install venv
python3 -m venv envmcpiedit # Create venv (eg. envmcpiedit)
source envmcpiedit/bin/activate # Activate venv
pip3 install mutf8 pynbt # Install required modules in Active venv
~/.mcpiedit/mcpiedit # Run mcpiedit in Active venv
deactivate # Deactivate venv

# Run mcpiedit
source envmcpiedit/bin/activate # Activate venv (envmcpiedit)
~/.mcpiedit/mcpiedit # Run mcpiedit
deactivate # Deactivate venv
```

**Comment by TkTech** [comment]
All of these look like people forgetting to install the dependencies rather than any issue with pycraft/pynbt/mutf8.
