### ISSUE TITLE
Getting this when executing start.py

### ISSUE THREAD

**Issue by AlfieC** [ammaraskar/pyCraft#29]
Exception in thread Networking Thread:
Traceback (most recent call last):
  File "/usr/lib/python3.2/threading.py", line 740, in _bootstrap_inner
    self.run()
  File "/root/pyCraft/minecraft/networking/connection.py", line 179, in run
    self.connection.file_object)
  File "/root/pyCraft/minecraft/networking/connection.py", line 215, in read_packet
    packet_data.send(stream.read(length))
  File "/usr/lib/python3.2/codecs.py", line 300, in decode
    (result, consumed) = self._buffer_decode(data, self.errors, final)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xa2 in position 18: invalid start byte

**Comment by ammaraskar** [comment]
From a quick guess, I think its a python3 compatibility problem. Will look into it tomorrow.

**Comment by ammaraskar** [comment]
Note to self:

``socket.makefile`` in py3 requires an encoding
