### ISSUE TITLE
Test suite fails on windows

### ISSUE THREAD

**Issue by ammaraskar** [ammaraskar/pyCraft#64]
Haven't been on a windows machine in a while but this is what happens running the test suite on it, I'm assuming it has to do with how getsockname is implemented on windows but I'll look into it.

```
Traceback (most recent call last):
  File "C:\Users\ammar\workspace\pyCraft\tests\test_connection.py", line 62, in _test_connect
    self._test_connect_client(client, cond)
  File "C:\Users\ammar\workspace\pyCraft\tests\test_connection.py", line 83, in _test_connect_client
    client.connect()
  File "C:\Users\ammar\workspace\pyCraft\minecraft\networking\connection.py", line 245, in connect
    self._connect()
  File "C:\Users\ammar\workspace\pyCraft\minecraft\networking\connection.py", line 275, in _connect
    self.socket.connect((self.options.address, self.options.port))
OSError: [WinError 10049] The requested address is not valid in its context
```

**Comment by ammaraskar** [comment]
Looks like the relevant bit is that connecting to `0.0.0.0` is not possible on windows.
