### ISSUE TITLE
Failed building wheel for pycraft

### ISSUE THREAD

**Issue by trenton3983** [ammaraskar/pyCraft#69]
here's the error.

```
pip install pycraft
Collecting pycraft
  Downloading PyCraft-1503040.tar.bz2
Building wheels for collected packages: pycraft
  Running setup.py bdist_wheel for pycraft ... error
  Complete output from command E:\Anaconda3\python.exe -u -c "import setuptools, tokenize;__file__='C:\\Users\\TRENTO~1.MCK\\AppData\\Local\\Temp\\pip-build-v0lrago1\\pycraft\\setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" bdist_wheel -d C:\Users\TRENTO~1.MCK\AppData\Local\Temp\tmpi1oyibdhpip-wheel- --python-tag cp36:
  running bdist_wheel
  running build
  running build_py
  creating build
  creating build\lib
  creating build\lib\pycraft
  copying Src\anvil.py -> build\lib\pycraft
  copying Src\geometry.py -> build\lib\pycraft
  copying Src\low.py -> build\lib\pycraft
  copying Src\nbt.py -> build\lib\pycraft
  copying Src\__init__.py -> build\lib\pycraft
  installing to build\bdist.win-amd64\wheel
  running install
  running install_lib
  creating build\bdist.win-amd64
  creating build\bdist.win-amd64\wheel
  creating build\bdist.win-amd64\wheel\pycraft
  copying build\lib\pycraft\anvil.py -> build\bdist.win-amd64\wheel\.\pycraft
  copying build\lib\pycraft\geometry.py -> build\bdist.win-amd64\wheel\.\pycraft
  copying build\lib\pycraft\low.py -> build\bdist.win-amd64\wheel\.\pycraft
  copying build\lib\pycraft\nbt.py -> build\bdist.win-amd64\wheel\.\pycraft
  copying build\lib\pycraft\__init__.py -> build\bdist.win-amd64\wheel\.\pycraft
  running install_data
  creating build\bdist.win-amd64\wheel\PyCraft-1503040.data
  creating build\bdist.win-amd64\wheel\PyCraft-1503040.data\data
  Traceback (most recent call last):
    File "<string>", line 1, in <module>
    File "C:\Users\TRENTO~1.MCK\AppData\Local\Temp\pip-build-v0lrago1\pycraft\setup.py", line 42, in <module>
      keywords = ["Minecraft"],
    File "E:\Anaconda3\lib\distutils\core.py", line 148, in setup
      dist.run_commands()
    File "E:\Anaconda3\lib\distutils\dist.py", line 955, in run_commands
      self.run_command(cmd)
    File "E:\Anaconda3\lib\distutils\dist.py", line 974, in run_command
      cmd_obj.run()
    File "E:\Anaconda3\lib\site-packages\wheel\bdist_wheel.py", line 215, in run
      self.run_command('install')
    File "E:\Anaconda3\lib\distutils\cmd.py", line 313, in run_command
      self.distribution.run_command(command)
    File "E:\Anaconda3\lib\distutils\dist.py", line 974, in run_command
      cmd_obj.run()
    File "E:\Anaconda3\lib\site-packages\setuptools-27.2.0-py3.6.egg\setuptools\command\install.py", line 61, in run
    File "E:\Anaconda3\lib\distutils\command\install.py", line 557, in run
      self.run_command(cmd_name)
    File "E:\Anaconda3\lib\distutils\cmd.py", line 313, in run_command
      self.distribution.run_command(command)
    File "E:\Anaconda3\lib\distutils\dist.py", line 974, in run_command
      cmd_obj.run()
    File "E:\Anaconda3\lib\distutils\command\install_data.py", line 56, in run
      dir = convert_path(f[0])
    File "E:\Anaconda3\lib\distutils\util.py", line 125, in convert_path
      raise ValueError("path '%s' cannot be absolute" % pathname)
  ValueError: path '/usr/share/doc/pycraft' cannot be absolute

  ----------------------------------------
  Failed building wheel for pycraft
  Running setup.py clean for pycraft
Failed to build pycraft
Installing collected packages: pycraft
  Running setup.py install for pycraft ... error
    Complete output from command E:\Anaconda3\python.exe -u -c "import setuptools, tokenize;__file__='C:\\Users\\TRENTO~1.MCK\\AppData\\Local\\Temp\\pip-build-v0lrago1\\pycraft\\setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record C:\Users\TRENTO~1.MCK\AppData\Local\Temp\pip-qf_nroi1-record\install-record.txt --single-version-externally-managed --compile:
    running install
    running build
    running build_py
    creating build
    creating build\lib
    creating build\lib\pycraft
    copying Src\anvil.py -> build\lib\pycraft
    copying Src\geometry.py -> build\lib\pycraft
    copying Src\low.py -> build\lib\pycraft
    copying Src\nbt.py -> build\lib\pycraft
    copying Src\__init__.py -> build\lib\pycraft
    running install_lib
    creating E:\Anaconda3\Lib\site-packages\pycraft
    copying build\lib\pycraft\anvil.py -> E:\Anaconda3\Lib\site-packages\pycraft
    copying build\lib\pycraft\geometry.py -> E:\Anaconda3\Lib\site-packages\pycraft
    copying build\lib\pycraft\low.py -> E:\Anaconda3\Lib\site-packages\pycraft
    copying build\lib\pycraft\nbt.py -> E:\Anaconda3\Lib\site-packages\pycraft
    copying build\lib\pycraft\__init__.py -> E:\Anaconda3\Lib\site-packages\pycraft
    byte-compiling E:\Anaconda3\Lib\site-packages\pycraft\anvil.py to anvil.cpython-36.pyc
    byte-compiling E:\Anaconda3\Lib\site-packages\pycraft\geometry.py to geometry.cpython-36.pyc
    byte-compiling E:\Anaconda3\Lib\site-packages\pycraft\low.py to low.cpython-36.pyc
    byte-compiling E:\Anaconda3\Lib\site-packages\pycraft\nbt.py to nbt.cpython-36.pyc
    byte-compiling E:\Anaconda3\Lib\site-packages\pycraft\__init__.py to __init__.cpython-36.pyc
    running install_data
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "C:\Users\TRENTO~1.MCK\AppData\Local\Temp\pip-build-v0lrago1\pycraft\setup.py", line 42, in <module>
        keywords = ["Minecraft"],
      File "E:\Anaconda3\lib\distutils\core.py", line 148, in setup
        dist.run_commands()
      File "E:\Anaconda3\lib\distutils\dist.py", line 955, in run_commands
        self.run_command(cmd)
      File "E:\Anaconda3\lib\distutils\dist.py", line 974, in run_command
        cmd_obj.run()
      File "E:\Anaconda3\lib\site-packages\setuptools-27.2.0-py3.6.egg\setuptools\command\install.py", line 61, in run
      File "E:\Anaconda3\lib\distutils\command\install.py", line 557, in run
        self.run_command(cmd_name)
      File "E:\Anaconda3\lib\distutils\cmd.py", line 313, in run_command
        self.distribution.run_command(command)
      File "E:\Anaconda3\lib\distutils\dist.py", line 974, in run_command
        cmd_obj.run()
      File "E:\Anaconda3\lib\distutils\command\install_data.py", line 56, in run
        dir = convert_path(f[0])
      File "E:\Anaconda3\lib\distutils\util.py", line 125, in convert_path
        raise ValueError("path '%s' cannot be absolute" % pathname)
    ValueError: path '/usr/share/doc/pycraft' cannot be absolute

    ----------------------------------------
Command "E:\Anaconda3\python.exe -u -c "import setuptools, tokenize;__file__='C:\\Users\\TRENTO~1.MCK\\AppData\\Local\\Temp\\pip-build-v0lrago1\\pycraft\\setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record C:\Users\TRENTO~1.MCK\AppData\Local\Temp\pip-qf_nroi1-record\install-record.txt --single-version-externally-managed --compile" failed with error code 1 in C:\Users\TRENTO~1.MCK\AppData\Local\Temp\pip-build-v0lrago1\pycraft\
```

**Comment by ammaraskar** [comment]
See #63, the pyCraft package on pypi isn't us
