### ISSUE TITLE
EOFError on connect()

### ISSUE THREAD

**Issue by DashLt** [ammaraskar/pyCraft#77]
I have the following worker function:
```
 def worker(account, server, port=25565):
    token = authentication.AuthenticationToken()
    token.authenticate(*account)
    print "Logged in as {0}:{1}".format(*account)
    time.sleep(1)
    print "Attempting connection"
    connection = Connection(server, port, auth_token=token)
    connection.connect()
    time.sleep(1)
    packet = serverbound.play.ChatPacket()
    packet.message = "test"
    connection.write_packet(packet)
    time.sleep(1)
    connection.disconnect()
```

Upon calling this from an interpreter:  
`worker(("email", "password"), "server", port)`  
I am able to login, but upon attempting connection, I receive this error:
```Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 801, in __bootstrap_inner
    self.run()
  File "/usr/local/lib/python2.7/dist-packages/minecraft/networking/connection.py", line 397, in run
    self.connection._handle_exception(e, sys.exc_info())
  File "/usr/local/lib/python2.7/dist-packages/minecraft/networking/connection.py", line 363, in _handle_exception
    raise_(*exc_info)
  File "/usr/local/lib/python2.7/dist-packages/minecraft/networking/connection.py", line 395, in run
    self._run()
  File "/usr/local/lib/python2.7/dist-packages/minecraft/networking/connection.py", line 426, in _run
    self.connection.file_object, timeout=read_timeout)
  File "/usr/local/lib/python2.7/dist-packages/minecraft/networking/connection.py", line 475, in read_packet
    length = VarInt.read(stream)
  File "/usr/local/lib/python2.7/dist-packages/minecraft/networking/types.py", line 96, in read
    raise EOFError("Unexpected end of message.")
EOFError: Unexpected end of message.
```

On the server side, I join and then immediately disconnect.
Server is running Spigot on 1.12.2.

**Comment by ammaraskar** [comment]
Does it work if you don't send the chat packet? If so, it might be the case that you're sending it too early, before the client has fully connected. Take a look at the approach here that waits for the server to spawn you before sending a packet: https://github.com/ammaraskar/pyCraft/issues/62#issuecomment-312612789

**Comment by joodicator** [comment]
I'm closing this issue for now. Feel free to post further comments if you believe there's more to discuss.
